/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "a.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "strtok.h"

void assert_strtok(char *s1, char *s2, char *delim) {
  ck_assert_str_eq(strtok(s1, delim), strtok(s2, delim));
}

START_TEST(strtok1) {
  char s1[] = "Hello, world!";
  char s2[] = "Hello, world!";
  char delim[] = "!";
  assert_strtok(s1, s2, delim);
}
END_TEST

START_TEST(strtok2) {
  char s1[] = "Hello, world!";
  char s2[] = "Hello, world!";
  char delim[] = "\0";
  assert_strtok(s1, s2, delim);
}
END_TEST

START_TEST(strtok3) {
  char s1[] = "Hello, world!";
  char s2[] = "Hello, world!";
  char delim[] = " ";
  assert_strtok(s1, s2, delim);
}
END_TEST

START_TEST(strtok4) {
  char s1[] = "Hello, \0world!";
  char s2[] = "Hello, \0world!";
  char delim[] = " ";
  assert_strtok(s1, s2, delim);
}
END_TEST

START_TEST(strtok5) {
  char s1[] = "Hello, world!";
  char s2[] = "Hello, world!";
  char delim[] = "o";
  assert_strtok(s1, s2, delim);
}
END_TEST

START_TEST(strtok6) {
  char s1[] = "Hello, world!!!!!";
  char s2[] = "Hello, world!!!!!";
  char delim[] = "!";
  assert_strtok(s1, s2, delim);
}
END_TEST

START_TEST(strtok7) {
  char s1[] = "\0";
  char s2[] = "\0";
  char delim[] = " ";
  ck_assert_ptr_eq(strtok(s1, delim), s21_NULL);
  ck_assert_ptr_eq(strtok(s2, delim), s21_NULL);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, strtok1);
    tcase_add_test(tc1_1, strtok2);
    tcase_add_test(tc1_1, strtok3);
    tcase_add_test(tc1_1, strtok4);
    tcase_add_test(tc1_1, strtok5);
    tcase_add_test(tc1_1, strtok6);
    tcase_add_test(tc1_1, strtok7);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}