/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "a.check" instead.
 */

#include <check.h>

#line 1 "a.check"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "strlen.h"

START_TEST(strlen1)
{
#line 7
char string[]="Hello, world!";
ck_assert_int_eq(strlen(string), s21_strlen(string));

}
END_TEST

START_TEST(strlen2)
{
#line 7
char string[]=" ";
ck_assert_int_eq(strlen(string), s21_strlen(string));

}
END_TEST

START_TEST(strlen3)
{
#line 7
char string[]="\0";
ck_assert_int_eq(strlen(string), s21_strlen(string));

}
END_TEST

START_TEST(strlen4)
{
#line 7
char string[]="\n";
ck_assert_int_eq(strlen(string), s21_strlen(string));

}
END_TEST

START_TEST(strlen5)
{
#line 7
char string[]="Hello, world!";
ck_assert_int_eq(strlen(string), s21_strlen(string));

}
END_TEST


int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, strlen1);
    tcase_add_test(tc1_1, strlen2);
    tcase_add_test(tc1_1, strlen3);
    tcase_add_test(tc1_1, strlen4);
    tcase_add_test(tc1_1, strlen5);
    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
