/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "a.check" instead.
 */

#include <check.h>

#line 1 "a.check"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "strcat.h"


START_TEST(strncat1)
{
#line 8
char a[50] = "Hello";
const char b[] = "world!";
s21_size_t c = 4;
ck_assert_str_eq(strncat(a, b , c), s21_strncat(a,b, c));

}
END_TEST

START_TEST(strncat2)
{
#line 14
char a[50] = "Hello ";
const char b[] = "";
s21_size_t c = 0;
ck_assert_str_eq(strncat(a, b , c), s21_strncat(a,b, c));

}
END_TEST

START_TEST(strncat3)
{
#line 20
char a[50] = "Hello";
const char b[] = "wor\0ld!";
s21_size_t c = 6;
ck_assert_str_eq(strncat(a, b , c), s21_strncat(a,b, c));

}
END_TEST

START_TEST(strncat4)
{
#line 26
char a[50] = "Hello";
const char b[] = "\0world!";
s21_size_t c = 6;
ck_assert_str_eq(strncat(a, b , c), s21_strncat(a,b, c));

}
END_TEST

START_TEST(strncat5)
{
#line 32
char a[50] = "Hello";
const char b[] = "world!\0";
s21_size_t c = 6;
ck_assert_str_eq(strncat(a, b , c), s21_strncat(a,b, c));

}
END_TEST

START_TEST(strncat6)
{
#line 38
char a[50] = "Hello ";
const char b[] = "world!";
s21_size_t c =  strlen(b);
ck_assert_str_eq(strncat(a, b , c), s21_strncat(a,b, c));

}
END_TEST

START_TEST(strncat7)
{
#line 44
char a[50] = "Hello ";
const char b[] = "world!";
s21_size_t c = 3;
ck_assert_str_eq(strncat(a, b , c), s21_strncat(a,b, c));

}
END_TEST

START_TEST(strncat8)
{
#line 50
char a[50] = "12,15, ";
const char b[] = "18";
s21_size_t c = 3;
ck_assert_str_eq(strncat(a, b , c), s21_strncat(a,b, c));


 
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, strncat1);
    tcase_add_test(tc1_1, strncat2);
    tcase_add_test(tc1_1, strncat3);
    tcase_add_test(tc1_1, strncat4);
    tcase_add_test(tc1_1, strncat5);
    tcase_add_test(tc1_1, strncat6);
    tcase_add_test(tc1_1, strncat7);
    tcase_add_test(tc1_1, strncat8);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
