/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "a.check" instead.
 */

#include <check.h>

#line 1 "a.check"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "memchr.h"


START_TEST(memchr1)
{
#line 8
const char *string = "Hello, world!";
    int item = 'o';
    size_t count = strlen(string);

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);

}
END_TEST

START_TEST(memchr2)
{
#line 18
const char *string = "Hello, world!";
    int item = 'o';
    size_t count = strlen(string);

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);

}
END_TEST

START_TEST(memchr3)
{
#line 28
const char *string = "Hello, world!";
    int item = 'o';
    size_t count = strlen(string);

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);    

}
END_TEST

START_TEST(memchr4)
{
#line 38
const char *string = "Hello, world!";
    int item = 'o';
    size_t count = strlen(string);

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);

}
END_TEST

START_TEST(memchr5)
{
#line 48
const char *string = "Hello, world!";
    int item = 'o';
    size_t count = strlen(string);

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);

}
END_TEST

START_TEST(memchr6)
{
#line 58
const char *string = "Hello, world!";
    int item = 'o';
    size_t count = strlen(string);

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);

}
END_TEST

START_TEST(memchr7)
{
#line 68
const char *string = "Hello, world!";
    int item = 'o';
    size_t count = strlen(string);

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);

}
END_TEST

START_TEST(memchr8)
{
#line 78
const char *string = "12547945325\063256";
    int item = '6';
    size_t count = strlen(string);

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);

}
END_TEST

START_TEST(memchr9)
{
#line 88
const char *string = " ";
    int item = '6';
    size_t count = strlen(string);

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);

}
END_TEST

START_TEST(memchr10)
{
#line 98
const char *string = "Hello, cat!";
    int item = 't';
    size_t count = 60 ;

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);

}
END_TEST

START_TEST(memchr11)
{
#line 108
const char *string = "Hello, \0cat!";
    int item = 't';
    size_t count = strlen(string) + 10;

    void *result1 = memchr(string, item, count);
    void *result2 = s21_memchr(string, item, count);

    ck_assert_ptr_eq(result1, result2);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, memchr1);
    tcase_add_test(tc1_1, memchr2);
    tcase_add_test(tc1_1, memchr3);
    tcase_add_test(tc1_1, memchr4);
    tcase_add_test(tc1_1, memchr5);
    tcase_add_test(tc1_1, memchr6);
    tcase_add_test(tc1_1, memchr7);
    tcase_add_test(tc1_1, memchr8);
    tcase_add_test(tc1_1, memchr9);
    tcase_add_test(tc1_1, memchr10);
    tcase_add_test(tc1_1, memchr11);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
