/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "a.check" instead.
 */

#include <check.h>

#line 1 "a.check"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "memset.h"


START_TEST(memset1)
{
#line 8
char a[] = "Hello";
char b[] = "Hello";
s21_size_t c = 5;
char value = 'A';
ck_assert_str_eq(memset(a, value, c), s21_memset(a, value, c));

}
END_TEST

START_TEST(memset2)
{
#line 15
char a[10];
char b[10];
s21_size_t c = 5;
char value = 'x';
ck_assert_str_eq(memset(a, value, c), s21_memset(a, value, c));

}
END_TEST

START_TEST(memset3)
{
#line 22
char a[10] = {0};
char b[10] = {0};
s21_size_t c = 5;
char value = 'A';
ck_assert_str_eq(memset(a, value, c), s21_memset(a, value, c));

}
END_TEST

START_TEST(memset4)
{
#line 29
char a[] = "Hello";
char b[] = "Hello";
s21_size_t c = 5;
char value = '\0';
ck_assert_str_eq(memset(a, value, c), s21_memset(a, value, c));

}
END_TEST

START_TEST(memset5)
{
#line 36
char a[10] = {0};
char b[10] = {0};
s21_size_t c = 10;
char value = 'p';
ck_assert_str_eq(memset(a, value, c), s21_memset(a, value, c));

}
END_TEST

START_TEST(memset6)
{
#line 43
char a[10] = "Hello";
char b[10] = "Hello";
s21_size_t c = 1;
char value = 'p';
ck_assert_str_eq(memset(a, value, c), s21_memset(a, value, c));

}
END_TEST

START_TEST(memset7)
{
#line 50
char a[10] = "Hello";
char b[10] = "Hello";
s21_size_t c = 5;
char value = -1;
ck_assert_str_eq(memset(a, value, c), s21_memset(a, value, c));

}
END_TEST

START_TEST(memset8)
{
#line 57
char a[100] = {0};
char b[100] = {0};
s21_size_t c = 1;
char value = 'F';
ck_assert_str_eq(memset(a, value, c), s21_memset(a, value, c));

}
END_TEST

START_TEST(memset9)
{
#line 64
char a[10] = {0};
char b[10] = {0};
s21_size_t c = 5;
char value = 128;
ck_assert_str_eq(memset(a, value, c), s21_memset(a, value, c));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, memset1);
    tcase_add_test(tc1_1, memset2);
    tcase_add_test(tc1_1, memset3);
    tcase_add_test(tc1_1, memset4);
    tcase_add_test(tc1_1, memset5);
    tcase_add_test(tc1_1, memset6);
    tcase_add_test(tc1_1, memset7);
    tcase_add_test(tc1_1, memset8);
    tcase_add_test(tc1_1, memset9);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
