/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "a.check" instead.
 */

#include <check.h>

#line 1 "a.check"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cmp.h"


START_TEST(memcmp1)
{
#line 8
const char str1[] = "hello";
const char str2[] = "hello";
s21_size_t size = 5;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, 0);

}
END_TEST

START_TEST(memcmp2)
{
#line 16
const char str1[] = "hello world";
const char str2[] = "hello cat";
s21_size_t size = 10;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, 1);

}
END_TEST

START_TEST(memcmp3)
{
#line 24
const char str1[] = "hello ";
const char str2[] = "hello cat, dog";
s21_size_t size = 7;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, 0);

}
END_TEST

START_TEST(memcmp4)
{
#line 32
const char str1[] = "hello";
const char str2[] = "hello";
s21_size_t size = 0;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, 0);

}
END_TEST

START_TEST(memcmp5)
{
#line 40
const char str1[] = "cat";
const char str2[] = "cct";
s21_size_t size = 5;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, -1);

}
END_TEST

START_TEST(memcmp6)
{
#line 48
const char str1[] = "he\0llo";
const char str2[] = "he\0llo";
s21_size_t size = 7;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, 0);

}
END_TEST

START_TEST(memcmp7)
{
#line 56
const char str1[] = "h\ello";
const char str2[] = "h\ello";
s21_size_t size = 5;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, 0);

}
END_TEST

START_TEST(memcmp8)
{
#line 64
const char str1[] = "hello";
const char str2[] = "hello";
s21_size_t size = 6;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, 0);

}
END_TEST

START_TEST(memcmp9)
{
#line 72
const char str1[] = "\fkkfdv\\kjf";
const char str2[] = "\fkkfdv\\kjf";
s21_size_t size = 5;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, 0);

}
END_TEST

START_TEST(memcmp10)
{
#line 80
const char str1[] = " ";
const char str2[] = "hello";
s21_size_t size = 0;

int result = s21_memcmp(str1, str2, size);
ck_assert_int_eq(result, 0);

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, memcmp1);
    tcase_add_test(tc1_1, memcmp2);
    tcase_add_test(tc1_1, memcmp3);
    tcase_add_test(tc1_1, memcmp4);
    tcase_add_test(tc1_1, memcmp5);
    tcase_add_test(tc1_1, memcmp6);
    tcase_add_test(tc1_1, memcmp7);
    tcase_add_test(tc1_1, memcmp8);
    tcase_add_test(tc1_1, memcmp9);
    tcase_add_test(tc1_1, memcmp10);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
